# Stubbl Identity

image: Visual Studio 2017

skip_tags: true

configuration:
  - Release

build_script:
  - ps: .\build.ps1

test: off

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 77Ama9JRrneE6Rq94zj7AO4NN09+kC2jIl8S7/gPgBW7yBrmxwehO+GPQR7RFCeIatJ1cMjJrKojFhD+RaNvJZa6jho1RNbWWVDh3bgPcOg=

for:

-
  branches:
    only:
      - master

  version: 0.1.10

  deploy:
    - provider: Environment
      name: stubbl-production-uksouth-identity__staging

-
  branches:
    except:
    - master

  version: 0.1.10.{build}-{branch}